import Head from "next/head";
import { BsSearch } from "react-icons/bs";

import Card from "../components/Card/Card";
import Header from "../components/Header/Header";
import Pagintation from "../components/Pagination/Pagintation";
import SectionWrapper from "../components/SectionWrapper/SectionWrapper";
import { activeAgents, topAgents } from "../data/agents";
import { blogs } from "../data/blogs,js";
import { chatWithAgent, chooseAgent } from "../data/chooseAgent";

import styles from "../styles/Home.module.css";

const Blogs = () => {
  return (
    <article className={`container ${styles.blogs__container}`}>
      <h2 className={styles.blog__title}>Latest Articles by Agents</h2>

      <article className={styles.blogs__wrapper}>
        {blogs.map((blog, index) => (
          <Card cardType="blogCard" key={index} {...blog} />
        ))}
      </article>

      <Pagintation />
    </article>
  );
};

export default function Home() {
  return (
    <article className={styles.container}>
      <Head>
        <title>Agent Book | Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SectionWrapper {...topAgents} />
      <Card cardType="horizontalCard" {...chooseAgent} />
      <SectionWrapper {...activeAgents} />

      <article className={styles.local__agent__belt}>
        <article className="container">
          <article className={styles.local__agent__details}>
            <h2 className={styles.title}>Connect with an expert local agent</h2>
            <p className={styles.description}>
              Our agents are here to help you. Let’s make your home <br />
              search or sale easier.
            </p>
          </article>

          <article className={styles.searchbar__wrapper}>
            <input type="text" placeholder="Search by name or location" />
            <button className={styles.search__button}>
              <BsSearch />
            </button>
          </article>
        </article>
      </article>

      <Card cardType="horizontalCard" {...chatWithAgent} />

      <Blogs />
    </article>
  );
}
